# time in minutes below...
Minimum players before game starts: 2
Time before games starts: '1:00'
Game time: '15:00'
Alpha Core Block ID: 153
Death Messages:
- "This faggot named PLAYER died by the master supreme god [KILLER]"
- "PLAYER you fucken gumpy shit. You died again."
- "Christ PLAYER, stop fucking dieing. God."
Spawns: