name: ShiftSpawn
version: 1.3.0-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.shiftspawn.ShiftSpawn
description: Recognises order in which players join server and be able to set spawnpoints for them when the game begins.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
depend: [FeatherBoard]
commands:
  shiftspawn:
    aliases: [sp]
permissions:
  shiftspawn.*:
    default: op