name: ShiftSpawn
version: 1.2.1-PREALPHA-SNAPSHOT
main: com.gmail.gogobebe2.shiftspawn.ShiftSpawn
description: Recognises order in which players join server and be able to set spawnpoints for them when the game begins.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  shiftspawn:
    description: Set minigame spawns.
  test:
permissions:
  shiftspawn.*:
    default: op